import { expect, test } from '@playwright/test'
import { boot } from './gate'

test('the ambiguity and early BM outcomes are computed and explained', async ({ page }) => {
  await boot(page)
  await page.getByRole('button', { name: 'Shared prefix' }).click()
  await expect(page.locator('#fixture-view')).toContainText('1001')
  await expect(page.locator('#fixture-view')).toContainText('next bits are 1 and 0')
  await page.getByRole('button', { name: 'Early failure' }).click()
  await expect(page.locator('#fixture-view')).toContainText('first fails at offset')
  await page.getByRole('button', { name: 'Early success' }).click()
  await expect(page.locator('#fixture-view')).toContainText('All 64 forecast bits match')
})

test('a sufficient single-register capture is frozen, checked, confirmed, and retired on new evidence', async ({ page }) => {
  await boot(page)
  await page.getByRole('button', { name: 'Collect to 24 bits' }).click()
  await expect(page.locator('#hidden-view')).toContainText('Observed N = 24')
  await page.getByRole('button', { name: 'Freeze hidden forecast' }).click()
  await expect(page.locator('[data-verdict="PREFIX FITTED"]')).toBeVisible()
  await expect(page.locator('[data-claim="single-actual"]')).toContainText('Not revealed')
  const predicted = await page.locator('[data-claim="single-prediction"]').innerText()
  expect(predicted).toMatch(/^[01]{64}$/)
  await page.getByRole('button', { name: 'Reveal original next 64 bits' }).click()
  expect(await page.locator('[data-claim="single-actual"]').innerText()).toBe(predicted)
  expect(await page.locator('[data-claim="single-prediction"]').innerText()).toBe(predicted)
  await expect(page.locator('[data-verdict="NEXT 64 BITS PREDICTED"]')).toBeVisible()
  await page.getByRole('button', { name: 'Compare original parameters' }).click()
  await expect(page.locator('[data-verdict="LFSR PARAMETERS CONFIRMED"]')).toBeVisible()
  await page.getByRole('button', { name: 'Collect to 24 bits' }).click()
  await expect(page.locator('[data-verdict="LFSR PARAMETERS CONFIRMED"]')).toBeVisible()
  await page.getByRole('button', { name: 'Collect one bit' }).click()
  await expect(page.locator('[data-verdict="LFSR PARAMETERS CONFIRMED"]')).toHaveCount(0)
  await expect(page.locator('#single-view')).toContainText('Collect a hidden prefix')
})

test('user-entered sequence has analysis without a ground-truth verdict', async ({ page }) => {
  await boot(page)
  await page.getByLabel('Binary sequence').fill('001101110')
  await page.getByRole('button', { name: 'Analyze entered sequence' }).click()
  await expect(page.locator('#bm-view')).toContainText('User-entered sequence')
  await expect(page.locator('[data-claim="bm-length"]')).toHaveText('5')
  await expect(page.locator('[data-claim="manual-candidate"]')).toHaveText(/^[01]{32}$/)
  await expect(page.locator('[data-verdict="NEXT 64 BITS PREDICTED"]')).toHaveCount(0)
  await page.getByLabel('Binary sequence').fill('00110x')
  await page.getByRole('button', { name: 'Analyze entered sequence' }).click()
  await expect(page.locator('#manual-error')).toContainText('only 0 and 1')
  await page.getByLabel('Binary sequence').fill('')
  await page.getByRole('button', { name: 'Analyze entered sequence' }).click()
  await expect(page.locator('#bm-view')).toContainText('User-entered sequence · N = 0')
  await expect(page.locator('[data-claim="manual-candidate"]')).toHaveText('0'.repeat(32))
})

test('the negative-claim fixture passes construction checks while exposing recovered secret state', async ({ page }) => {
  await boot(page)
  await page.getByRole('button', { name: 'Reproducible claim fixture' }).click()
  await expect(page.locator('[data-verdict="ONE TRIPLE WITHIN SEARCH BUDGET"]')).toBeVisible()
  await expect(page.locator('[data-claim="attack-n"]')).toHaveText('300')
  await expect(page.locator('#attack-view')).toContainText('R1 states scored 127')
  await expect(page.locator('#attack-view')).toContainText('R3 states scored 8191')
  const work = (await page.locator('#attack-view').innerText()).match(/bit comparisons (\d+)/i)
  expect(Number(work?.[1]), 'measured comparisons include both complete correlation scans').toBeGreaterThanOrEqual((127 + 8191) * 300)
  const frozen = await page.locator('[data-claim="geffe-prediction"]').innerText()
  expect(frozen).toMatch(/^[01]{64}$/)
  await page.getByRole('button', { name: 'Reveal original next 64 bits' }).click()
  expect(await page.locator('[data-claim="geffe-actual"]').innerText()).toBe(frozen)
  expect(await page.locator('[data-claim="geffe-prediction"]').innerText()).toBe(frozen)
  await expect(page.locator('[data-verdict="NEXT 64 BITS PREDICTED"]')).toBeVisible()
  await page.getByRole('button', { name: 'Compare original states' }).click()
  await expect(page.locator('[data-verdict="GEFFE STATES CONFIRMED"]')).toBeVisible()
  await page.getByRole('button', { name: 'Measure later complexity with 466 bits' }).click()
  await expect(page.locator('[data-claim="later-complexity"]')).toHaveText('233')
  await expect(page.locator('[data-verdict="CONSTRUCTION CHECKS PASSED"]')).toContainText('Truth-table rows 8/8')
  await expect(page.locator('[data-verdict="CONSTRUCTION CHECKS PASSED"]')).toContainText('127 / 2047 / 8191')
  await expect(page.locator('[data-claim="negative"]')).toContainText("This Geffe generator's nonlinearity and high linear complexity do not prevent recovery of its secret state.")
  await expect(page.locator('[data-claim="attack-n"]')).toHaveText('300')
  await expect(page.locator('#attack-view')).toContainText('Later inspection total 466 bits')
  await expect(page.locator('#attack-view .verdict.failure')).toHaveCount(0)
})

test('a cancelled scan cannot publish a stale verdict into a new session', async ({ page }) => {
  await boot(page)
  await page.getByRole('button', { name: 'Reproducible claim fixture' }).click()
  await page.getByRole('button', { name: 'Cancel scan' }).click()
  await page.getByRole('button', { name: 'New hidden Geffe session' }).click()
  await expect(page.locator('#attack-view')).toContainText('Attack capture: 300')
  await expect(page.locator('[data-verdict="ONE TRIPLE WITHIN SEARCH BUDGET"]')).toHaveCount(0)
})
